### PR TITLE
Add py.typed objects to the python SDK

### PR DESCRIPTION
**Pull request by vdurmont**
I have no idea if this will work... Any idea on how to test it?

### CODE REVIEW

**Review by jklein24 — APPROVED** [review]
Looks fine to me, but I know nothing about how this stuff works, so good to wait for @mgorven on this one haha.

**Comment by mgorven** [comment]
I'm not familiar with `py.typed`; what's the goal here?

**Comment by jklein24** [comment]
> I'm not familiar with `py.typed`; what's the goal here?

@mgorven The Ripio folks reported that our SDK isn't marked typed because apparently we need to distribute it with a py.typed file in order for types to be parsed in consuming applications: https://peps.python.org/pep-0561/

**Comment by mgorven** [comment]
I think the `py.typed` file is only needed at the package top level (`lightspark/py.typed`). The PEP says "This marker applies recursively: if a top-level package includes it, all its sub-packages MUST support type checking as well."

**Comment by vdurmont** [comment]
Updated the PR to remove useless recursive `py.typed` files.

**Review by mgorven — APPROVED** [review]

**Pull request merged**
